package main

import "fmt"

/*
EX-026: You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t. (Leetcode #389)

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

func main() {
	fmt.Println(findTheDifference("abcd", "abcde"))
	fmt.Println(findTheDifference("", "y"))
}

func findTheDifference(s string, t string) byte {
	freq := [26]int{}
	var result byte

	for _, r := range s {
		freq[r-'a']++
	}

	for _, r := range t {
		freq[r-'a']--
	}

	for i, v := range freq {
		if v == -1 {
			return byte(i + 'a')
		}
	}
	return result
}

// Takeaway: Nothing special. You can solve it with XOR's too, think about that.
